CREATE TABLE EMPLEADO_FOTO
(
    RUT_EMPLEADO VARCHAR2(10) NOT NULL,
    FOTO         BLOB DEFAULT EMPTY_BLOB()
);


DECLARE
    V_BLOB       BLOB;
    V_BFILE      BFILE;
    V_NOMARCHIVO VARCHAR2(10);
BEGIN
    INSERT INTO EMPLEADO_FOTO VALUES ('20439684-1', EMPTY_BLOB()) RETURNING FOTO INTO V_BLOB;
    V_BFILE := BFILENAME('ORACLECLRDIR', 'Kumamon.png');
    DBMS_LOB.OPEN(V_BFILE, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.LOADFROMFILE(V_BLOB, V_BFILE, DBMS_LOB.GETLENGTH(V_BFILE));
    DBMS_LOB.CLOSE(V_BFILE);
END;

SELECT *
FROM EMPLEADO_FOTO;
